name: analytics_web
description: AngularDart analytics dashboard web app
version: 0.0.1
author: Jaime Loeuf <jaimeloeuf@gmail.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  angular: ^5.2.0
  angular_components: ^0.11.0
  angular_router: any
  firebase_web: ^5.0.9

dev_dependencies:
  angular_test: ^2.2.0
  build_runner: ^1.1.2
  build_test: ^0.10.3
  build_web_compilers: ^1.0.0
  test: ^1.5.1
